spring.application.name=AdventureXP
spring.datasource.url=jdbc:postgresql://localhost:5432/adventure_db
spring.datasource.username=adventure_user
spring.datasource.password=adventure_pass
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
